GRANT ALL ON SCHEMA public TO whatschat;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO whatschat;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO whatschat;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO whatschat;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO whatschat;
