version: "3.8"

services:
  postgres:
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: whatschat
      POSTGRES_PASSWORD: whatschat123
      POSTGRES_DB: whatschat
    volumes:
      - ../../scripts/db/init-grants.sql:/docker-entrypoint-initdb.d/02-init-grants.sql:ro

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
