name: whatschat
description: 一个完整的 WhatsApp 克隆应用
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理
  provider: ^6.0.3

  # 图片处理
  cached_network_image: ^3.2.0

  # UI组件
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  adaptive_theme: ^3.4.1

  # 时间和日期
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
