"""Embedding service for generating text embeddings."""
import logging
from typing import Optional

import ollama
from openai import AsyncOpenAI

from src.config import get_settings

logger = logging.getLogger(__name__)


class EmbeddingService:
    """Service for generating text embeddings using Ollama or OpenAI."""

    def __init__(self) -> None:
        settings = get_settings()
        self._provider = settings.embedding_provider
        self._model = settings.embedding_model
        self._openai_model = settings.openai_embedding_model

        if self._provider == "openai":
            self._openai_client = AsyncOpenAI(api_key=settings.openai_api_key)
        elif self._provider == "ollama":
            self._ollama_client = ollama.AsyncClient(
                host=settings.ollama_base_url
            )
        else:
            raise ValueError(f"Unsupported embedding provider: {self._provider}")

        logger.info(
            f"EmbeddingService initialized with provider: {self._provider}"
        )

    async def embed(self, texts: list[str]) -> list[list[float]]:
        """
        Generate embeddings for a list of texts.

        Args:
            texts: List of text strings to embed

        Returns:
            List of embedding vectors
        """
        if not texts:
            return []

        if self._provider == "ollama":
            return await self._embed_ollama(texts)
        else:
            return await self._embed_openai(texts)

    async def embed_single(self, text: str) -> list[float]:
        """
        Generate embedding for a single text.

        Args:
            text: Text string to embed

        Returns:
            Embedding vector
        """
        embeddings = await self.embed([text])
        return embeddings[0] if embeddings else []

    async def _embed_ollama(self, texts: list[str]) -> list[list[float]]:
        """Generate embeddings using Ollama."""
        embeddings = []
        for text in texts:
            try:
                response = await self._ollama_client.embeddings(
                    model=self._model,
                    prompt=text,
                )
                embeddings.append(response["embedding"])
            except Exception as e:
                logger.error(f"Ollama embedding failed for text: {e}")
                raise

        return embeddings

    async def _embed_openai(self, texts: list[str]) -> list[list[float]]:
        """Generate embeddings using OpenAI."""
        try:
            response = await self._openai_client.embeddings.create(
                model=self._openai_model,
                input=texts,
            )
            return [item.embedding for item in response.data]
        except Exception as e:
            logger.error(f"OpenAI embedding failed: {e}")
            raise

    async def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by the current model.

        Returns:
            Embedding dimension
        """
        settings = get_settings()

        if self._provider == "ollama":
            try:
                info = await self._ollama_client.show(
                    model=self._model,
                )
                info_dict = info if isinstance(info, dict) else {"dimension": settings.qdrant_vector_size}
                return info_dict.get("dimension", settings.qdrant_vector_size)
            except Exception:
                return settings.qdrant_vector_size
        else:
            if self._openai_model == "text-embedding-3-small":
                return 1536
            elif self._openai_model == "text-embedding-3-large":
                return 3072
            elif self._openai_model == "text-embedding-ada-002":
                return 1536
            return settings.qdrant_vector_size

    async def health_check(self) -> bool:
        """Check if the embedding service is healthy."""
        try:
            test_embedding = await self.embed_single("health check")
            return len(test_embedding) > 0
        except Exception as e:
            logger.error(f"Embedding service health check failed: {e}")
            return False


# Singleton instance
_embedding_service: Optional[EmbeddingService] = None


def get_embedding_service() -> EmbeddingService:
    """Get or create embedding service instance."""
    global _embedding_service
    if _embedding_service is None:
        _embedding_service = EmbeddingService()
    return _embedding_service
